#!/usr/bin/env python

import re
import sys
import argparse

import tcolorlib

def rgb_to_ansi((r,g,b), background=False):
    if args.ansi256:
        return tcolorlib.rgb_to_ansi_256colors((r,g,b), background)
    else:
        return tcolorlib.rgb_to_ansi_truecolor((r,g,b), background)

def highlight(all_patterns, line):
    line_fbcolor = ""
    for pattern in all_patterns:
        if pattern["kind"] == 'foreground-line' and re.search(pattern["regex"], line):
            line_fbcolor += rgb_to_ansi(pattern["rgb_color"])
        elif pattern["kind"] == 'background-line' and re.search(pattern["regex"], line):
            line_fbcolor += rgb_to_ansi(pattern["rgb_color"])
    for pattern in all_patterns:
        if pattern["kind"] == 'foreground':
            line = re.sub(pattern["regex"], rgb_to_ansi(pattern["rgb_color"]) + "\g<0>" + (line_fbcolor or tcolorlib.ANSI_RESET_COLOR), line, count=0)
        elif pattern["kind"] == 'background':
            line = re.sub(pattern["regex"], rgb_to_ansi(pattern["rgb_color"], background=True) + "\g<0>" + (line_fbcolor or tcolorlib.ANSI_RESET_COLOR), line, count=0)
    if line_fbcolor:
        return line_fbcolor + line + tcolorlib.ANSI_RESET_COLOR
    else:
        return line

def load_patterns(args):
    def load(color, regex, kind):
        rgb_color = tcolorlib.webcolor_to_rgb(color)
        if not rgb_color:
            print "ERROR: invalid color '%s'" % color
            sys.exit(1)
        all_patterns.append({
            "regex": regex,
            "kind": kind,
            "rgb_color": rgb_color
        })

    all_patterns = []
    for (color, regex) in args.color_pattern:
        load(color, regex, "foreground")
    for (color, regex) in args.bgcolor_pattern:
        load(color, regex, "background")
    for (color, regex) in args.color_pattern_line:
        load(color, regex, "foreground-line")
    for (color, regex) in args.bgcolor_pattern_line:
        load(color, regex, "background-line")
    return all_patterns

def set_color_support_defaults():
    try:
        issue = open("/etc/issue").read()
        if "Ubuntu 14.04" in issue:
            # gnome-terminal supports true color by default but it needs to be
            # linked to libvte >= 0.36 which isn't the case for ubuntu 14.04
            args.ansi256 = True
    except:
        pass

def main():
    set_color_support_defaults()

    all_patterns = load_patterns(args)
    sys.stdout.write(tcolorlib.ANSI_RESET_COLOR)
    while True:
        line = sys.stdin.readline()
        if not line:
            break

        line = highlight(all_patterns, line)

        print line,

if __name__ == '__main__':
    try:
        parser = argparse.ArgumentParser()
        parser.add_argument("--color-pattern", nargs=2, metavar="COLOR REGEX", action='append', default=[])
        parser.add_argument("--bgcolor-pattern", nargs=2, metavar="COLOR REGEX", action='append', default=[])
        parser.add_argument("--color-pattern-line", nargs=2, metavar="COLOR REGEX", action='append', default=[])
        parser.add_argument("--bgcolor-pattern-line", nargs=2, metavar="COLOR REGEX", action='append', default=[])
        parser.add_argument("--ansi256", help="fallback to 256 color mode (useful if your terminal doesn't support ANSI escape codes for proper RGB colors)")
        args = parser.parse_args()
        sys.exit(main())
    except KeyboardInterrupt:
        pass
